# Generated by Django 4.2.7 on 2023-12-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
    ]
